---
physicalFunctions:
  0000:01:00.0:
    capabilities:
      - intel
      - 10G
    services:
      - service-1
    virtualFunctions:
      0000:01:00.1: 1
  0000:02:00.0:
    capabilities:
      - intel
      - 20G
    services:
      - service-1
      - service-2
    virtualFunctions:
      0000:02:00.1: 1
      0000:02:00.2: 2
      0000:02:00.3: 3
