---
resources:
  - networkServiceName: service1.example.com
    sourceHostName: example.org
    sourcePCIAddress: 0000:01:00:0
    capability: 10G
    targetMACAddress: 00:0a:95:9d:68:16
  - networkServiceName: service2.example.com
    sourceHostName: example.org
    sourcePCIAddress: 0000:02:00:0
    capability: 100G
    targetMACAddress: 00:1b:44:11:3a:b7
