---
name: Update dependent repositories
on:
  push:
    branches:
      - master
jobs:
  update-dependent-repositories:
    strategy:
      matrix:
        repository: [cmd-forwarder-sriov, cmd-nsc]
    name: Update ${{ matrix.repository }}
    runs-on: ubuntu-latest
    needs:
      - automerge
    if: github.actor == 'nsmbot' && github.base_ref == 'master' && github.event_name == 'pull_request'
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
          fetch-depth: '0'
      - name: Create commit message
        working-directory: ${{ github.repository }}
        run: |
          echo "Update go.mod and go.sum to latest version from ${{ github.repository }}@master ${{ github.repository }}#${{ steps.findPr.outputs.pr }}" >> /tmp/commit-message
          echo "" >> /tmp/commit-message
          echo "${{ github.repository }} PR link: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}" >> /tmp/commit-message
          echo "" >> /tmp/commit-message
          echo "${{ github.repository }} commit message:" >> /tmp/commit-message
          git log master... >> /tmp/commit-message
          echo "Commit Message:"
          cat /tmp/commit-message
      - name: Checkout networkservicemesh/${{ matrix.repository }}
        uses: actions/checkout@v2
        with:
          path: networkservicemesh/${{ matrix.repository }}
          repository: networkservicemesh/${{ matrix.repository }}
          token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Update ${{ github.repository }} locally
        working-directory: networkservicemesh/${{ matrix.repository }}
        run: |
          GOPROXY=direct go get -u github.com/${{ github.repository }}
          go mod tidy
          git diff
      - name: Push update to the ${{ matrix.repository }}
        working-directory: networkservicemesh/${{ matrix.repository }}
        run: |
          echo Starting to update repositotry ${{ matrix.repository }}
          git config --global user.email "nsmbot@networkservicmesh.io"
          git config --global user.name "NSMBot"
          git add go.mod go.sum
          git commit -s -F /tmp/commit-message
          git checkout -b update/${{ github.repository }}
          git push -f origin update/${{ github.repository }}
